// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzhtyJPZCffc4yfnfEepjys5ahdbrTTGc',
    appId: '1:566490580489:web:c429662aca8eda7a3e9ad8',
    messagingSenderId: '566490580489',
    projectId: 'appmarinauta',
    authDomain: 'appmarinauta.firebaseapp.com',
    databaseURL: 'https://appmarinauta-default-rtdb.firebaseio.com',
    storageBucket: 'appmarinauta.firebasestorage.app',
    measurementId: 'G-665Q6MBQYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkpXSAte2GRQKccz68L9eXk02p8N3WRkw',
    appId: '1:566490580489:android:86eeb26a6281641b3e9ad8',
    messagingSenderId: '566490580489',
    projectId: 'appmarinauta',
    databaseURL: 'https://appmarinauta-default-rtdb.firebaseio.com',
    storageBucket: 'appmarinauta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFosx-ejHGi5AhSodVFhwZHvFBc5akpKo',
    appId: '1:566490580489:ios:1dc64bc8737d592e3e9ad8',
    messagingSenderId: '566490580489',
    projectId: 'appmarinauta',
    databaseURL: 'https://appmarinauta-default-rtdb.firebaseio.com',
    storageBucket: 'appmarinauta.firebasestorage.app',
    androidClientId: '566490580489-6q5hd9rmkan6p2c1pc7al2cnmui7iofd.apps.googleusercontent.com',
    iosClientId: '566490580489-104nojacqeho86d0c1rfclgdfu4bsn86.apps.googleusercontent.com',
    iosBundleId: 'com.example.marinautaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFosx-ejHGi5AhSodVFhwZHvFBc5akpKo',
    appId: '1:566490580489:ios:1dc64bc8737d592e3e9ad8',
    messagingSenderId: '566490580489',
    projectId: 'appmarinauta',
    databaseURL: 'https://appmarinauta-default-rtdb.firebaseio.com',
    storageBucket: 'appmarinauta.firebasestorage.app',
    androidClientId: '566490580489-6q5hd9rmkan6p2c1pc7al2cnmui7iofd.apps.googleusercontent.com',
    iosClientId: '566490580489-104nojacqeho86d0c1rfclgdfu4bsn86.apps.googleusercontent.com',
    iosBundleId: 'com.example.marinautaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzhtyJPZCffc4yfnfEepjys5ahdbrTTGc',
    appId: '1:566490580489:web:6770d50fa950ccaf3e9ad8',
    messagingSenderId: '566490580489',
    projectId: 'appmarinauta',
    authDomain: 'appmarinauta.firebaseapp.com',
    databaseURL: 'https://appmarinauta-default-rtdb.firebaseio.com',
    storageBucket: 'appmarinauta.firebasestorage.app',
    measurementId: 'G-QSFRXXMQZG',
  );

}